version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: deal_or_no_deal
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    command: [nginx, "-g", "daemon off;"]
